# Stub for `open3d.cpu.pybind.geometry` — the surface this workspace touches.
# See `typings/open3d/__init__.pyi` for why this exists.

from collections.abc import Iterator
from typing import Any

import numpy as np
from numpy.typing import NDArray

__all__ = ["PointCloud", "TriangleMesh"]

class Vector3dVector:
    """A `(N, 3)` float64 matrix passed through Open3D's pybind boundary.

    Open3D stores point/mesh attributes in this type; `np.asarray` on it
    yields the backing `(N, 3)` array, and `len` gives the row count.
    """

    def __init__(self, value: NDArray[np.float64] | list[list[float]]) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NDArray[np.float64]]: ...
    def __getitem__(self, index: int) -> NDArray[np.float64]: ...

class Vector3iVector:
    """A `(N, 3)` int32 matrix of triangle indices."""

    def __init__(self, value: NDArray[np.int32] | list[list[int]]) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[NDArray[np.int32]]: ...
    def __getitem__(self, index: int) -> NDArray[np.int32]: ...

class Geometry3D:
    def is_empty(self) -> bool: ...
    def dimension(self) -> int: ...

class PointCloud(Geometry3D):
    def __init__(self) -> None: ...
    points: Vector3dVector
    normals: Vector3dVector
    colors: Vector3dVector
    def has_points(self) -> bool: ...
    def has_normals(self) -> bool: ...
    def has_colors(self) -> bool: ...

class TriangleMesh(Geometry3D):
    def __init__(self) -> None: ...
    vertices: Vector3dVector
    triangles: Vector3iVector
    vertex_normals: Vector3dVector
    triangle_normals: Vector3dVector
    vertex_colors: Vector3dVector
    def has_vertices(self) -> bool: ...
    def has_triangles(self) -> bool: ...
    def has_vertex_normals(self) -> bool: ...
    def has_triangle_normals(self) -> bool: ...
    def has_vertex_colors(self) -> bool: ...
    def compute_vertex_normals(self) -> TriangleMesh: ...
    def compute_triangle_normals(self) -> TriangleMesh: ...
    def paint_uniform_color(self, color: NDArray[np.float64]) -> TriangleMesh: ...
    def translate(self, translation: NDArray[np.float64]) -> TriangleMesh: ...
    def rotate(
        self, R: NDArray[np.float64], center: NDArray[np.float64]
    ) -> TriangleMesh: ...
    def scale(self, scale: float, center: NDArray[np.float64]) -> TriangleMesh: ...
    def transform(self, transformation: NDArray[np.float64]) -> TriangleMesh: ...
    def is_watertight(self) -> bool: ...
    def is_edge_manifold(self) -> bool: ...
    def get_volume(self) -> float: ...
    def get_surface_area(self) -> float: ...
    def get_axis_aligned_bounding_box(self) -> Any: ...
    def get_oriented_bounding_box(self) -> Any: ...
    def sample_points_uniformly(self, number_of_points: int) -> PointCloud: ...
    def sample_points_poisson_disk(
        self, number_of_points: int, init_factor: int
    ) -> PointCloud: ...
    @staticmethod
    def create_from_point_cloud_poisson(
        pointcloud: PointCloud, depth: int
    ) -> tuple[TriangleMesh, NDArray[np.float64]]: ...
